version: '3.8'

services:
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      DatabaseSettings__ConnectionString: mongodb://catalogdb:27017
      DatabaseSettings__DatabaseName: CatalogDb
      DatabaseSettings__BrandsCollection: Brands
      DatabaseSettings__TypesCollection: Types
      DatabaseSettings__ProductsCollection: Products

  catalogdb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdata:/data/db

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    command: redis-server --appendonly yes

    ports:
      - "6379:6379"
    volumes:
      - basket-data:/data
  discountdb:
    image: postgres:16
    container_name: discountdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password@1
      POSTGRES_DB: DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL","pg_isready -U admin -d DiscountDb"]
       interval: 10s
       timeout: 5s
       retries: 5

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderdb
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd123"

    restart: always
    ports:
      - "1433:1433"
    volumes:
      - orderdb-data:/var/opt/mssql
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' -b -o /dev/null"]
        interval: 15s
        timeout: 10s
        retries: 20
        start_period: 180s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: Password@1
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/Basket/Basket.API/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - basketdb
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      CacheSettings__connectionString: basketdb:6379
      GrpcSettings__DiscountUrl: http://discount.api:8080
      EventBusSettings__HostAddress: "amqp://guest:guest@rabbitmq:5672"
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: services/Discount/Discount.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      DatabaseSettings__ConnectionString: Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1
    container_name: discount.api
    depends_on:
        discountdb:
           condition: service_healthy
    ports:
     - "8084:8080"

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: services/Ordering/Ordering.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__OrderingConnectionString: Server=orderdb;Database=OrderDb2;User Id=sa;Password=P@ssw0rd123;TrustServerCertificate=True;
      EventBusSettings__HostAddress: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      orderdb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8086:8080"
volumes:
  catalogdata:
  postgres_data:
  pgadmin_data:
  orderdb-data:
  basket-data:
